<a href="https://colab.research.google.com/github/sudam802/NLP_tutorials/blob/main/Countervectorizor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd

In [28]:
# data
documents = [
    "I love machine learning",
    "Machine learning is fascinating",
    "I love coding in Python"
]


In [36]:
# making the vocabulary
words=[word  for sentence in documents  for word in sentence.split()]
vocab=set(words)
vocab=list(vocab)
print(vocab)
print(type(vocab))

['Python', 'machine', 'love', 'in', 'is', 'learning', 'Machine', 'I', 'coding', 'fascinating']
<class 'list'>


In [30]:
#  creating the counter vectorizor
#  creating an empty array
num_words=len(vocab)
num_docs=len(documents)
vec=np.zeros((num_docs,num_words))
print(vec)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
for i in enumerate(documents):
  for word in i[1].split():
    pos=vocab.index(word)
    vec[i[0]][pos]=1
print(vec)

[[0. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 1.]
 [1. 0. 1. 1. 0. 0. 0. 1. 1. 0.]]
